#:kivy 2.0.0
<MiSpinner>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        Label:
            id: click_label
            text: 'Elegir destino'
            font_size: 32

        Spinner:
            id: spinner_id
            text: 'Vacaciones de invierno'
            values: ['Ushuaia', 'El Calafate', 'Bariloche', 'Mendoza']

            on_text: root.spinner_click(spinner_id.text)
